### PR TITLE
This script can print any pattern on the fly given by user input

### PR DESCRIPTION
**Pull request by alphasingh**

### CODE REVIEW

**Comment by pyGuru123** [comment]
write what modules need to be installed in a form of comment

**Comment by alphasingh** [comment]
No module is needed, I've used an existing pattern printer contributed by another contributor

**Comment by pyGuru123** [comment]
Add this file / module Patterns.Alphabets_pattern, wrap your all files for this PR in a folder

**Comment by alphasingh** [comment]
already added the module in first line, I will put comments along with screenshot in pattern screenshots

**Comment by alphasingh** [comment]
will move this script files in folder

**Pull request closed without merging**
